all: oftps oftpc di
oftps: oftps.c
	cc -Wall -ansi -pedantic -O3 -o oftps oftps.c -lc
	-strip -s oftps
oftpc: oftpc.c
	cc -Wall -ansi -pedantic -O3 -o oftpc oftpc.c -lc
	-strip -s oftpc
di: di.c
	cc -Wall -ansi -pedantic -O3 -o di di.c
	-strip -s di
